In [ ]:
cd /content/drive/MyDrive/edu/Flask

/content/drive/MyDrive/edu/Flask


In [ ]:
# 데이터 불러오기
import pandas as pd
data = pd.read_csv('price_data.csv')

data.head()

year  avg_temp  min_temp  max_temp  rain_fail  avg_price
0  20170101        -3        -3        -2         13        248
1  20170102        -1        -1        -1          5        131
2  20170103        -2        -1        -1          8        166
3  20170104        -3        -3        -1         16        199
4  20170105        -2        -3        -2         20        168

In [ ]:
# 데이터 타입 변경
import numpy as np
xy = np.array(data, dtype=np.float32)
xy[:5, :]

array([[ 2.0170100e+07, -3.0000000e+00, -3.0000000e+00, -2.0000000e+00,
         1.3000000e+01,  2.4800000e+02],
       [ 2.0170102e+07, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         5.0000000e+00,  1.3100000e+02],
       [ 2.0170104e+07, -2.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         8.0000000e+00,  1.6600000e+02],
       [ 2.0170104e+07, -3.0000000e+00, -3.0000000e+00, -1.0000000e+00,
         1.6000000e+01,  1.9900000e+02],
       [ 2.0170104e+07, -2.0000000e+00, -3.0000000e+00, -2.0000000e+00,
         2.0000000e+01,  1.6800000e+02]], dtype=float32)

In [ ]:
# xy 분할
x_data = xy[:, 1:-1]
y_data = xy[:, [-1]]

display(x_data[:5])
display(y_data[:5])

array([[-3., -3., -2., 13.],
       [-1., -1., -1.,  5.],
       [-2., -1., -1.,  8.],
       [-3., -3., -1., 16.],
       [-2., -3., -2., 20.]], dtype=float32)

array([[248.],
       [131.],
       [166.],
       [199.],
       [168.]], dtype=float32)

In [ ]:
# 모델 구축
import tensorflow as tf
from tensorflow.keras import layers, optimizers, Sequential

def create_model():
    model = Sequential([layers.Dense(50, activation='relu', input_shape=(4,)),
                        layers.Dense(20, activation='relu'),
                        layers.Dense(1)])
    model.compile(loss='mse', optimizer=optimizers.Adam(lr=0.0001))
    return model

In [ ]:
model = create_model()
model.fit(x_data, y_data, epochs=5, batch_size=5)

Epoch 1/5
18/18 [==============================] - 0s 1ms/step - loss: 26003.4640
Epoch 2/5
18/18 [==============================] - 0s 1ms/step - loss: 24790.7668
Epoch 3/5
18/18 [==============================] - 0s 2ms/step - loss: 23273.5230
Epoch 4/5
18/18 [==============================] - 0s 1ms/step - loss: 25121.0241
Epoch 5/5
18/18 [==============================] - 0s 1ms/step - loss: 27235.8316


In [ ]:
# 학습 모델 저장1
# 모델의 모든 정보를 저장하기에 추후 model 구축이 필요하지 않음
model.save('./models/model.h5')

In [ ]:
# 학습 모델 저장2
# 가중치만 저장하고자 한다면 체크포인트로 저장하여야 함
model.save_weights('./models/my_checkpoint')