In [1]:
pwd

'/content'

In [3]:
cd /content/drive/MyDrive/edu/Flask

/content/drive/MyDrive/edu/Flask


In [37]:
# import modules
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, svm, metrics

# The digits dataset
train=pd.read_csv('C:/Users/dojun/Documents/data/mnist/train.csv')
data_test=pd.read_csv('C:/Users/dojun/Documents/data/mnist/test.csv')

data_train = train.iloc[:,1:].values
label_train = train.iloc[:,0].values

data_test = data_test.values
	
data_train[data_train>0] = 1
data_test[data_test>0] = 1

print(data_train)
print(label_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[1 0 1 ... 7 6 9]


In [6]:
# Create a classifier: a support vector classifier
classifier = svm.SVC(C=200,kernel='rbf',gamma=0.01,cache_size=8000,probability=False)
#classifier = svm.SVC()

In [7]:
# training
classifier.fit(data_train, label_train)

SVC(C=200, break_ties=False, cache_size=8000, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [8]:
# Now predict the value of the digit on the second half:
predicted = classifier.predict(data_test)

df=pd.DataFrame(predicted)
df.index+=1
df.index.name='ImageId'
df.columns=['Label']
df.to_csv('./mnist/results.csv',header=True)

print(predicted)

[2 0 9 ... 3 9 2]


In [9]:
# 모델 저장
import joblib

joblib.dump(classifier, './models/mnist_svm.pkl')

['./models/mnist_svm.pkl']

# 사용자 데이터 예측

In [1]:
# 모델 불러오기
import joblib

model = joblib.load('./models/mnist_svm.pkl')

C:\Users\dojun\anaconda3\envs\python38\lib\site-packages\sklearn\base.py:313: UserWarning: Trying to unpickle estimator SVC from version 0.22.2.post1 when using version 0.22.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(


In [38]:
model.score(data_train, label_train)

1.0

In [32]:
import os
from PIL import Image
import numpy as np

loc = '../py_data/my_mnist/'
ls_data = os.listdir(loc)

#0~9까지 숫자 데이터 (10개)
ls_num = []
for data in ls_data:
    num = Image.open(loc+data).convert('L')
    num = np.array(num).reshape(-1)
    ls_num.append(num)
    
np_num = np.array(ls_num)
np_num.shape

(10, 784)

In [36]:
# 모든 데이터에 대하여 2를 예측
model.predict(np_num)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)