# tensorflow Tokenizer

In [100]:
import tensorflow as tf

In [74]:
t = tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True, split=' ', char_level=False, oov_token=None,
    document_count=0)

In [93]:
txt = ['I like her.', 'do you llke him?', 'you like her aren\'t you? do you?']
txt

['I like her.', 'do you llke him?', "you like her aren't you? do you?"]

In [94]:
t.fit_on_texts(txt)

In [95]:
t.word_index

{'you': 1,
 'like': 2,
 'him': 3,
 'do': 4,
 'her': 5,
 'i': 6,
 'llke': 7,
 "aren't": 8,
 'dont': 9,
 'haha': 10}

In [96]:
sequences = t.texts_to_sequences(txt)
sequences

[[6, 2, 5], [4, 1, 7, 3], [1, 2, 5, 8, 1, 4, 1]]

In [97]:
t.sequences_to_texts(sequences)

['i like her', 'do you llke him', "you like her aren't you do you"]

# padding

In [102]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

pad_sequences(sequences, padding='post')

array([[6, 2, 5, 0, 0, 0, 0],
       [4, 1, 7, 3, 0, 0, 0],
       [1, 2, 5, 8, 1, 4, 1]])

In [105]:
# maxlen 설정

pad_sequences(sequences, padding='post', maxlen=5, truncating='post')

array([[6, 2, 5, 0, 0],
       [4, 1, 7, 3, 0],
       [1, 2, 5, 8, 1]])

In [107]:
# value 설정

pad_sequences(sequences, padding='post', maxlen=10, truncating='post', value=999)

array([[  6,   2,   5, 999, 999, 999, 999, 999, 999, 999],
       [  4,   1,   7,   3, 999, 999, 999, 999, 999, 999],
       [  1,   2,   5,   8,   1,   4,   1, 999, 999, 999]])