# Numpy

In [1]:
import numpy as np

In [3]:
ls1 = [1, 2, 3, 4, 5, 6]
arr = np.array(ls1)

print(arr)
print(arr.shape)
print(type(arr))

[1 2 3 4 5 6]
(6,)
<class 'numpy.ndarray'>


In [4]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr1.shape)
print(type(arr1))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


# 배열 생성
- `zeros()`: 모든 값을 0으로 생성
- `ones()`: 모든 값을 1로 생성
- `full()`: 사용자가 지정한 값으로 생성
- `eye()`: 대각선 1, 나머지 0인 2차원 배열 생성 -> 단위 행렬
- `full_like()` : Return a new array with shape of input filled with value.
- `empty()` : Return a new uninitialized array.

In [6]:
arr1 = np.zeros((2, 3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr2 = np.ones((2, 3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
arr3 = np.full((2, 3), 10)
print(arr3)

[[10 10 10]
 [10 10 10]]


In [9]:
arr4 = np.eye(5)
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
arr5 = np.full_like(arr4, 10)
print(arr5)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]


In [12]:
arr6 = np.empty((2, 3))
print(arr6)

[[1. 1. 1.]
 [1. 1. 1.]]


- reshape()

In [16]:
arr = np.array(range(12)).reshape((3, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


- 슬라이싱

In [17]:
arr[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [18]:
arr[2:, 1:3]

array([[ 9, 10]])

In [24]:
arr[:3, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

- 정수 인덱싱

In [26]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr[[0, 2], [1, 3]]

array([ 1, 11])

In [27]:
arr[[0, 2, 1, 2], [1, 3, 3, 0]]

array([ 1, 11,  7,  8])

In [28]:
arr[0, 3]

3

- 불(bool) 인덱싱

In [29]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
ls1 = [[False, True, False, True], 
       [False, True, False, True], 
       [False, True, False, True]]

arr_bool = np.array(ls1)

arr[arr_bool]  # True에 해당하는 값만 출력 -> 홀수

array([ 1,  3,  5,  7,  9, 11])

In [36]:
arr_bool2 = (arr % 2 == 0)

In [37]:
arr_bool2

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [39]:
arr[arr_bool2]

array([ 0,  2,  4,  6,  8, 10])

In [40]:
arr[arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [47]:
ls1 = [0 ,1, 2, 3]
tmp_bool = (ls1 % 2 == 0)   # 리스트는 적용되지 않음, arrary에서만 가능

TypeError: unsupported operand type(s) for %: 'list' and 'int'

# 연산
- `add()`: 더하기
- `subtract()`: 빼기
- `multiply()`: 곱하기
- `divide()`: 나누기

In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [50]:
added1 = a + b
added2 = np.add(a, b)

print(added1)
print(added2)

[5 7 9]
[5 7 9]


In [51]:
subtracted1 = a - b
subtracted2 = np.subtract(a, b)

print(subtracted1)
print(subtracted2)

[-3 -3 -3]
[-3 -3 -3]


In [52]:
multiplied1 = a * b
multiplied2 = np.multiply(a, b)

print(multiplied1)
print(multiplied2)

[ 4 10 18]
[ 4 10 18]


In [54]:
divided1 = a / b
divided2 = np.divide(a, b)

print(divided1)
print(divided2)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


- `matmul()`: 행렬곱(matrix multiplication)

In [56]:
arr1 = np.array(range(12)).reshape(3, 4)
arr2 = np.array(range(12)).reshape(4, 3)

print(arr1)  # 3 x 4
print(arr2)  # 4 x 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [66]:
arr3 = np.matmul(arr1, arr2)
arr4 = np.dot(arr1, arr2)

print(arr3)  # 3 x 3
print(arr4)

32
32


- `dot()`: matmul()과 동일

In [62]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [65]:
arr3 = np.dot(arr1, arr2)
arr4 = np.matmul(arr1, arr2)

print(arr3)
print(arr4)

32
32


In [73]:
arr1 = np.array(range(1, 7)).reshape(2, 3)
arr2 = np.array(range(7, 13)).reshape(3, 2)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [74]:
dot1 = np.dot(arr1, arr2)
dot2 = np.matmul(arr1, arr2)

print(dot1)
print(dot2)

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [80]:
arr1 = np.arange(2*3).reshape(2, 3)
arr2 = np.arange(3*2).reshape(3, 2)

print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [81]:
dot1 = np.dot(arr1, arr2)
dot2 = np.matmul(arr1, arr2)

print(dot1)
print(dot2)

[[10 13]
 [28 40]]
[[10 13]
 [28 40]]


- 배열 연산

In [58]:
arr = np.array(range(1, 7)).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
summated = np.sum(arr)
summated

21

In [60]:
producted = np.prod(arr)
producted

720

In [61]:
summated1 = np.sum(arr, axis = 0)
summated2 = np.sum(arr, axis = 1)

print(summated1)
print(summated2)

[5 7 9]
[ 6 15]


- 강사님 이메일: sjd001@empas.com