# Numpy
- `pip install numpy`

- list

In [4]:
ls1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in ls1:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [6]:
for i in range(len(ls1)):
    for j in range(len(ls1[i])):
        print(ls1[i][j])

1
2
3
4
5
6
7
8
9


- numpy

In [13]:
import numpy as np

arr1 = np.array(ls1)

print(ls1)
print(arr1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
ls2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10]]
arr2 = np.array(ls2)

print(ls2)
print(arr2)  # 길이가 동일해야함
print(type(arr2))

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10]]
[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9]) list([10])]
<class 'numpy.ndarray'>


<ipython-input-16-a4c94b2570fc>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr2 = np.array(ls2)


In [19]:
import pandas as pd

df1 = pd.DataFrame(ls1)

display(ls1)
display(arr1)
display(df1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
print(len(ls1))
print(arr1.shape)
print(df1.shape)

3
(3, 3)
(3, 3)


In [25]:
print(arr1.size)  # 전체 데이터 개수
print(arr1.ndim)  # 데이터 차원

9
2


In [26]:
arr2 = np.zeros((2, 2))
arr2

array([[0., 0.],
       [0., 0.]])

In [27]:
arr3 = np.ones((2, 2))
arr3

array([[1., 1.],
       [1., 1.]])

In [28]:
arr3 = np.full((2, 2), 5)  # 특정 숫자로 채우기
arr3

array([[5, 5],
       [5, 5]])

In [29]:
tmp = np.eye(3)
tmp

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
tmp = np.eye(5)
tmp

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
tmp = np.array(range(20)).reshape(2, 10)
tmp

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [36]:
tmp = np.array(range(20)).reshape(2, -1)
tmp

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [37]:
tmp = np.array(range(20)).reshape(3, -1)  # 나누어 떨어지는 수로 입력하여야 함
tmp

ValueError: cannot reshape array of size 20 into shape (3,newaxis)

In [38]:
tmp = np.array(range(20)).reshape(4, 5)  # 나누어 떨어지는 수로 입력하여야 함
tmp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
print(tmp)
print(tmp[[0, 1]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


- 배열 읽기
`tmp[[0, 2], [1, 4]]`: 배열[[행], [열]]

In [50]:
print(tmp)
print(tmp[[0, 2], [1, 4]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 1 14]


In [40]:
info = ['홍길동', 33, '남', '이미나', 45, '여', '강진구', 60, '남']

arr = np.array(info).reshape(3, 3)
arr

array([['홍길동', '33', '남'],
       ['이미나', '45', '여'],
       ['강진구', '60', '남']], dtype='<U3')

In [42]:
arr[0][0]

'홍길동'

In [43]:
arr[[0, 0]]

array([['홍길동', '33', '남'],
       ['홍길동', '33', '남']], dtype='<U3')

In [44]:
arr[[0, 1]]

array([['홍길동', '33', '남'],
       ['이미나', '45', '여']], dtype='<U3')

In [46]:
arr[[0, 2]]

array([['홍길동', '33', '남'],
       ['강진구', '60', '남']], dtype='<U3')

In [47]:
arr[[1]]

array([['이미나', '45', '여']], dtype='<U3')

In [60]:
arr[[0, 1, 2], [0]]   # 이름만 출력하기

array(['홍길동', '이미나', '강진구'], dtype='<U3')

# numpy 연산

In [63]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]
[0.25 0.4  0.5 ]


In [71]:
arr1 = np.array(range(1, 10)).reshape(3, 3)
arr2 = np.arange(10, 19).reshape(3, 3)

print(arr1, end='\n\n')
print(arr2, end='\n\n')
print(arr1*arr2, end='\n\n')
print(np.dot(arr1, arr2), end='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]



In [78]:
print(np.sum(arr1))  # 전체 합
print(np.sum(arr1, axis=0))  # 열방향 합
print(np.sum(arr1, axis=1))  # 행방향 합

45
[12 15 18]
[ 6 15 24]


# 3차원 배열

In [81]:
tmp = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
arr = np.array(tmp)

print(arr)
print(arr.shape)
print(arr.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [82]:
arr[0, 0, 0]

1

In [83]:
# 여러 원소 출력
arr[[0, 1], [0, 1], [0, 1]]

array([1, 8])

In [87]:
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [85]:
print(np.max(arr))  # 최대값
print(np.max(arr[0]))

8
4


In [88]:
print(np.argmax(arr))  # 최대값의 위치값
print(np.argmax(arr[0]))

7
3


In [93]:
print(arr)
print(arr.sum())  # 전체의 합
print(arr.sum(axis=0))  # 1번째 차원의 합
print(arr.sum(axis=1))  # 2번째 차원의 합(열방향)
print(arr.sum(axis=2))  # 3번째 차원의 합(행방향)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
36
[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


# 2차원 배열

In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([[1, 2]])
arr4 = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
arr1 + arr2   # 같은 구조끼리 계산 가능

array([[2, 4],
       [6, 8]])

In [9]:
arr1 + arr3   # 1차원은 broadcasting

array([[2, 4],
       [4, 6]])

In [10]:
arr1 + arr4   # 배수 관계가 아닌 차원은 계산 불가

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [13]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([[1, 2], [3, 4]])

arr1 + arr2   # 행 broadcasting 불가능

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

arr1 + arr2   # 열 broadcasting 불가능

ValueError: operands could not be broadcast together with shapes (2,2) (4,2) 

- `np.arange()`

In [18]:
np.arange(10).reshape(5, -1)  # 5행 *열  (*자동계산)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
arr = np.array([1, 4, 5, 6, 7, 8, 14])

print(np.mean(arr))  # 평균

6.428571428571429
